#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApp.Resource", IsApplication=true)]

namespace WeatherApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::WeatherApp.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::WeatherApp.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int pref_temp_entries = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int pref_temp_values = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080008
			public const int action_refresh = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int action_settings = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int action_share = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int action_viewLocation = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int container = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int detail_text = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int fragment_forecast = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int list_item_forecast_textview = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int listview_forecast = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_detail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_item_forecast = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int detail = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int detail_fragment = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int forecastfragment = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int main = 2131165187;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int action_refresh = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int action_settings = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int action_share = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int action_viewLocation = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int hello_world = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int pref_location_default = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int pref_location_key = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int pref_location_label = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int pref_location_summary = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int pref_tempDialog_label = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int pref_temp_default = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int pref_temp_key = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int pref_temp_label = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int pref_temp_summary = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int title_activity_detail = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int pref_general = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
